# Generated by Django 4.0.1 on 2023-05-30 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relation Company - User',
                'verbose_name_plural': 'Relations Company - User',
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='users',
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(related_name='users', through='my_app.CompanyUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyusers',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.company'),
        ),
        migrations.AddField(
            model_name='companyusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='companyusers',
            unique_together={('company', 'user')},
        ),
    ]
