# Generated by Django 4.1.3 on 2023-05-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_userprofile_company_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='vendor',
            new_name='reseller',
        ),
    ]
